<a href="https://colab.research.google.com/github/NikunjNPatel/Deep-Learning/blob/main/Practice-Notebooks/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
print(torch.__version__)

2.11.0+cpu


In [2]:
scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [13]:
print(scalar.shape)
print(scalar.ndim)
print(scalar.item())

torch.Size([])
0
5


In [15]:
row_vector = torch.tensor([1,2,3])
print(row_vector)
print(row_vector.shape)
print(row_vector.ndim)

tensor([1, 2, 3])
torch.Size([3])
1


In [16]:
matrix = torch.tensor([[1,2,3],[2,4,3],[3,3,4]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)

tensor([[1, 2, 3],
        [2, 4, 3],
        [3, 3, 4]])
torch.Size([3, 3])
2


In [18]:
matrix[0][:]

tensor([1, 2, 3])

In [19]:
matrix[-1][-1]

tensor(4)

In [20]:
matrix[2]

tensor([3, 3, 4])

In [26]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1,1,2],
                        [4,0,3],
                        [3,3,3]]])

In [27]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([2, 3, 3])


In [28]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
tensor[0][1]

tensor([4, 5, 6])

In [30]:
tensor[1]

tensor([[1, 1, 2],
        [4, 0, 3],
        [3, 3, 3]])

In [34]:
random_tensor = torch.rand(size=(2,3))
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.4193, 0.8469, 0.1768],
        [0.9104, 0.7969, 0.9679]])
torch.Size([2, 3])
2


In [36]:
random_tensor = torch.randint(low=1, high=10,size=(2,3))
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[9, 6, 3],
        [5, 6, 2]])
torch.Size([2, 3])
2


In [37]:
random_torch_n = torch.randn(size=(3,3))
random_torch_n, random_torch_n.ndim, random_torch_n.shape

(tensor([[-0.9301, -1.1085, -1.4653],
         [ 0.4678,  1.1622,  0.1106],
         [-0.3007,  0.1094,  1.2042]]),
 2,
 torch.Size([3, 3]))

In [49]:
zeros = torch.zeros(size=(3,3))
zeros, zeros.ndim, zeros.shape, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 2,
 torch.Size([3, 3]),
 torch.float32)

In [48]:
ones = torch.ones(size=(4,3))
ones, ones.ndim, ones.shape, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 2,
 torch.Size([4, 3]),
 torch.float32)

In [42]:
torch.range(0,10)

/tmp/ipykernel_3575/497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
z = torch.arange(0,10)
z, z.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [50]:
x = torch.arange(0,20,2)
x, x.dtype

(tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]), torch.int64)

In [55]:
y = torch.zeros_like(input=x)
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
w = torch.ones_like(input=x)
w

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
float_32 = torch.tensor([2,3,4,5], dtype=torch.float32)
float_32.dtype

torch.float32

In [61]:
float_32 = torch.tensor([2,3,4,5], dtype=torch.float)
float_32.dtype

torch.float32

In [62]:
float_64 = torch.tensor([2,3,4,5], dtype=torch.double)
float_64.dtype

torch.float64

In [63]:
int_val = torch.tensor([2,3,4,5], dtype=torch.int)
int_val.dtype

torch.int32

In [64]:
int_val = torch.tensor([2,3,4,5], dtype=torch.int16)
int_val.dtype

torch.int16

In [66]:
var = torch.tensor([1,2,3], dtype=None, device=None, requires_grad=False)
var

tensor([1, 2, 3])

In [68]:
float_64_to_32 = float_64.type(torch.float)
float_64_to_32.dtype, float_64_to_32

(torch.float32, tensor([2., 3., 4., 5.]))

In [71]:
x1 = torch.randint(low=1, high=10, size=(3,3))
x2 = torch.randint(low=1, high=10, size=(3,3))
print(f"x1: {x1}")
print(f"x2: {x2}")

x1: tensor([[8, 5, 4],
        [8, 3, 7],
        [6, 3, 5]])
x2: tensor([[1, 2, 3],
        [5, 6, 4],
        [9, 3, 5]])


In [72]:
x1 + 2

tensor([[10,  7,  6],
        [10,  5,  9],
        [ 8,  5,  7]])

In [73]:
x1 * 2

tensor([[16, 10,  8],
        [16,  6, 14],
        [12,  6, 10]])

In [74]:
x1 + x2

tensor([[ 9,  7,  7],
        [13,  9, 11],
        [15,  6, 10]])

In [75]:
x1 * x2 # element wise multiplication

tensor([[ 8, 10, 12],
        [40, 18, 28],
        [54,  9, 25]])

In [76]:
x1 @ x2 # matrix multiplication

tensor([[69, 58, 64],
        [86, 55, 71],
        [66, 45, 55]])

In [77]:
x1 - x2

tensor([[ 7,  3,  1],
        [ 3, -3,  3],
        [-3,  0,  0]])

In [80]:
torch.dot(x1[:][0], x2[:][0])

tensor(30)

In [82]:
torch.mul(x1,x2) # element wise multiplication

tensor([[ 8, 10, 12],
        [40, 18, 28],
        [54,  9, 25]])

In [83]:
torch.matmul(x1,x2) # matrix multiplication

tensor([[69, 58, 64],
        [86, 55, 71],
        [66, 45, 55]])

In [84]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [91]:
torch.transpose(tensor_A,0,1)

tensor([[1, 3, 5],
        [2, 4, 6]])

In [94]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [99]:
torch.min(tensor_A), tensor_A.min()

(tensor(1), tensor(1))

In [100]:
torch.max(tensor_A), tensor_A.max()

(tensor(6), tensor(6))

In [98]:
tensor_A.type(torch.float).mean()

tensor(3.5000)

In [101]:
tensor_A.sum()

tensor(21)

In [102]:
tensor_A.argmax() # Gives index of maximum value

tensor(5)

In [105]:
tensor_A.reshape(-1)[5]

tensor(6)

In [103]:
tensor_A.argmin() # Gives index of maximum value

tensor(0)

In [106]:
tensor_A.reshape(-1)[0]

tensor(1)

In [108]:
x1 = torch.tensor([1,2,3])
x2 = torch.tensor([4,5,6])
torch.vstack((x1,x2))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [109]:
torch.hstack((x1,x2))

tensor([1, 2, 3, 4, 5, 6])

In [110]:
torch.stack([x1,x2], dim=0) # dim = 0, vertical stack

tensor([[1, 2, 3],
        [4, 5, 6]])

In [111]:
torch.stack([x1,x2], dim=1) # transporse and stack horizontally

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [114]:
x = torch.zeros(size=(2,1,3,1,2)) # Remove all single dimension
y = x.squeeze()
y.shape

torch.Size([2, 3, 2])

In [120]:
y.unsqueeze(dim=2).shape # Add single dimension at specified location at dim

torch.Size([2, 3, 1, 2])

In [122]:
y.unsqueeze(dim=1).shape

torch.Size([2, 1, 3, 2])

In [123]:
y.unsqueeze(dim=0).shape

torch.Size([1, 2, 3, 2])

In [126]:
x_org = torch.rand(size=(224,224,3))
x_permuted = x_org.permute(2,0,1) # Reshape with new dimension order
x_permuted.shape

torch.Size([3, 224, 224])

In [129]:
# numpy array to tensor
x = np.random.rand(2,3)
x, x.dtype

(array([[0.00652079, 0.38719521, 0.25741823],
        [0.29332015, 0.17284598, 0.97223033]]),
 dtype('float64'))

In [130]:
x_tensor = torch.from_numpy(x)
x_tensor, x_tensor.dtype

(tensor([[0.0065, 0.3872, 0.2574],
         [0.2933, 0.1728, 0.9722]], dtype=torch.float64),
 torch.float64)

In [132]:
x_numpy = x_tensor.numpy()
x_numpy

array([[0.00652079, 0.38719521, 0.25741823],
       [0.29332015, 0.17284598, 0.97223033]])

In [134]:
torch.manual_seed(42)
x1 = torch.rand(2,3)

torch.manual_seed(42)
x2 = torch.rand(2,3)

x1 == x2

tensor([[True, True, True],
        [True, True, True]])

In [1]:
!nvidia-smi

Sat Aug 22 11:03:04 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# check gpu access with pytorch

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# count number of gpus
torch.cuda.device_count()

1

In [7]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [9]:
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
tensor_cpu = tensor_gpu.cpu()
tensor_cpu.numpy()

array([1, 2, 3])